<?php

namespace App\Services;

class AuthorizationService
{
    private $rolePermissions = [
        'headquarters' => [
            'RND' => [
                'Section Officer' => [
                    'current-exam.create',
                    'current-exam.store',
                    'current-exam.edit',
                    'departments-masters',
                    'view-all-examination-services',
                    'exam-heading',
                    'completed-exam.index',
                    'department-officials.edit',
                    'exam-services.index',
                    'exam-services.create',
                    'exam-services.edit',
                    'exam-services.show',
                    'exam-services.toggle-status',
                    'current-exam.index',
                    'current-exam.create',
                    'current-exam.edit',
                    'current-exam.show',
                    'current-exam.toggle-status',
                    'current-exam.getExamByNotificationNo',
                    'my-exam.examTask',
                ],
            ],
            'APD' => [
                'Section Officer' => [
                    'upload-candidates-csv',
                    'download-expected-candidates',
                    'finalize-csv',
                    'downlaodConfirmedExamHalls',
                    'download-finalized-halls-csv',
                    'exam-heading',
                    'completed-exam.index',
                    'report-heading',
                    'candidate-attendance',
                    'attendance.dropdown',
                    'attendance.report',
                    'department-officials.edit',
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                    'apd-candidates.download-sample-csv',
                    'apd-candidates.upload-candidates-csv',
                    'apd-candidates.finalize-csv',
                    'apd-candidates.download-finalize-halls-sample-csv',
                    'apd-candidates.addl-cand-count',
                    'attendance.report.overall',
                ],
            ],
            'ID' => [
                'Section Officer' => [
                    'download-expected-candidates',
                    'update-percentage',
                    'download-candidates-count-updated',
                    'create-charted-vehicle-route',
                    'edit-charted-vehicle-route',
                    'create-escort-staff',
                    'district.index',
                    'district.create',
                    'district.edit',
                    'district.toggle-status',
                    'district.show',
                    'view-all-chief-invigilators',
                    'district-masters',
                    'view-all-other-list',
                    'venues-masters',
                    'view-all-venue',
                    'center-filters',
                    'ci-filter',
                    'ci-district-filter',
                    'treasury-officers-filter',
                    'mobile-team-staffs-filter',
                    'departments-masters',
                    'confirmExamVenueHalls',
                    'downlaodConfirmedExamHalls',
                    'heading',
                    'view-all-examination-services',
                    'district-filter',
                    'view-all-department',
                    'exam-heading',
                    'completed-exam.index',
                    'report-heading',
                    'candidate-attendance',
                    'attendance.report.overall',
                    'attendance.dropdown',
                    'attendance.report',
                    'cv-down-updates',
                    'bundle-collection',
                    'omr-qca-delivered',
                    'replacement-omr-qca',
                    'omr-account.report',
                    'omr-report.report.overall',
                    'emergency-alrm',
                    'emergency-alarm-notification.report',
                    'exam-discrepancy',
                    'exam-material-discrepancy.report',
                    'candidate-remarks',
                    'candidate-remarks.report',
                    'candidate-remarks.report.overall',
                    'candidate-statement',
                    'consolidated-statement.report',
                    'report.consolidated.view',
                    'expenditure-statment',
                    'expenditure-statment.report',
                    'filter.expenditure',
                    'report.view',
                    'ci-meeting',
                    'ci-attendace.report',
                    'ci-attendace.report.overall',
                    'chv-routes',
                    'email-template',
                    'route-edit',
                    'cv-routes-report',
                    'download-meeting-qr',
                    'create-ci-meetings',
                    'create-vechicle-route',
                    'ci-assistant.index',
                    'ci-assistant.create',
                    'ci-assistant.edit',
                    'ci-assistant.show',
                    'ci-assistant.toggle-status',
                    'role.index',
                    'role.create',
                    'role.edit',
                    'ci-checklist.index',
                    'ci-checklist.create',
                    'ci-checklist.edit',
                    'ci-checklist.toggle-status',
                    'treasury-officers.index',
                    'treasury-officers.create',
                    'treasury-officers.edit',
                    'treasury-officers.show',
                    'treasury-officers.toggle-status',
                    'centers.index',
                    'centers.create',
                    'centers.edit',
                    'centers.show',
                    'centers.toggle-status',
                    'mobile-team.index',
                    'mobile-team.create',
                    'mobile-team.edit',
                    'mobile-team.show',
                    'mobile-team.toggle-status',
                    'venues.index',
                    'venues.create',
                    'venues.edit',
                    'venues.show',
                    'venues.destroy',
                    'venues.toggle-status',
                    'invigilators.index',
                    'invigilators.create',
                    'invigilators.edit',
                    'invigilators.show',
                    'invigilators.toggle-status',
                    'scribes.index',
                    'scribes.create',
                    'scribes.edit',
                    'scribes.show',
                    'scribes.toggle-status',
                    'chief-invigilators.index',
                    'chief-invigilators.create',
                    'chief-invigilators.edit',
                    'chief-invigilators.show',
                    'chief-invigilators.toggle-status',
                    'exam-services.index',
                    'exam-services.create',
                    'exam-services.edit',
                    'exam-services.show',
                    'exam-services.toggle-status',    
                    'department-officials.index',
                    'department-officials.create',
                    'department-officials.edit',
                    'department-officials.show',
                    'department-officials.toggle-status',    
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                    'id-candidates.update-percentage',
                    'id-candidates.download-updated-count-csv',
                    'id-candidates.intimateCollectorate',
                    'id-candidates.send-accommodation-email',
                    'id-candidates.show-venue-confirmation-form',
                    'id-candidates.save-venue-confirmation',
                    'id-candidates.export-confirmed-halls',
                    'id-candidates.send-mail',
                    'generate.qrcode',
                    'district-candidates.generatePdf',
                    'charted-vehicle-routes.index',
                    'charted-vehicle-route.generateTrunkboxOrder',
                    'charted-vehicle-routes.create',
                    'charted-vehicle-routes.edit',
                    'charted-vehicle-routes.view',
                    'charted-vehicle-routes.get-districts-for-exam',
                    'charted-vehicle-routes.downward-journey-routes',
                    'viewTrunkboxes',
                    'generateTrunkboxOrder',
                    'charted-vehicle-routes.getCvRoutesReport',
                    'charted-vehicle-routes.generateCvRoutesReport',
                    'id-candidates.edit-venue-consent',
                    'id-candidates.update-venue-consent',
                    'delivery-report.report',
                    'delivery-report.report.generate',
                    ],
            ],
            'ED' => [
                'Section Officer' => [
                    'verify-bundle-recevied-at-hq',
                    'exam-heading',
                    'cv-down-updates',
                    'completed-exam.index',
                    'bundle-collection',
                    'annexure-1-b.download',
                    'route-checkbox',
                    'department-officials.edit',
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                    'bundle-packaging.scan-chennai-disitrct-exam-materials',
                    'bundle-packaging.vanduty-staff-to-headquarters',
                    'scan-hq-exam-materials',
                    'charted-vehicle-routes.downward-journey-routes',
                    'charted.vehicle.verification',
                    'vehicel.report.download',
                    'viewTrunkboxes',
                    'charted-vehicle-routes.generateAnnexure1BReport',

                ],
            ],
            'VMD' => [
                'Section Officer' => [
                    'verify-materials-handovered',
                    'exam-heading',
                    'completed-exam.index',
                    'cv-down-updates',
                    'department-officials.edit',
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                    'bundle-packaging.save-handover-details',
                    'charted-vehicle-routes.downward-journey-routes',
                    'bundle-packaging.report-handover-details',
                ],
            ],
            'VSD' => [
                'Section Officer' => [
                    'report-heading',
                    'replacement-omr-qca',
                    'omr-account.report',
                    'omr-report.report.overall',
                    'department-officials.edit',
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                ],
            ],
            'MCD' => [
                'Section Officer' => [
                    'report-heading',
                    'emergency-alrm',
                    'emergency-alarm-notification.report',
                    'exam-discrepancy',
                    'exam-material-discrepancy.report',
                    'department-officials.edit',
                ],
            ],
            'QD' => [
                'Section Officer' => [
                    'upload-exam-materials-csv',
                    'download-exam-materials-uploaded',
                    'receive-materials-printer-to-hq',
                    'upload-trunk-box-otl-csv',
                    'download-trunk-box-otl-csv',
                    'exam-heading',
                    'completed-exam.index',
                    'omr-qca-delivered',
                    'create-exam-materails-route',
                    'create-exam-materials-route',
                    'department-officials.edit',
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                    'exam-materials.download-sample-csv',
                    'exam-materials.upload',
                    'exam-materials.index',
                    'receive-exam-materials.printer-to-hq-treasury',
                    'receive-exam-materials.scan-hq-exam-materials',
                    'exam-materials-route.index',
                    'exam-materials-route.create',
                    'exam-materials-route.edit',
                    'exam-materials-route.view',
                    'exam-trunkbox-qr-otl-data.index',
                    'exam-trunkbox-qr-otl-data.upload',
                    'exam-trunkbox-qr-otl-data.download-sample-csv',
                    'departments-masters',
                    'department-officials.index',
                    'department-officials.create',
                    'department-officials.edit',
                    'department-officials.show',
                    'chv-routes',
                    'charted-vehicle-routes.index',
                    'charted-vehicle-routes.edit',
                    'charted-vehicle-routes.view',
                    'department-officials.toggle-status',
                ],
            ],
            'ADMIN' => [
                'ci-meetings.*',
                'users.*'
            ],
            'VDS' => [
                'VDS' => [
                    'exam-heading',
                    'completed-exam.index',
                    'department-officials.edit',
                    'current-exam.index',
                    'current-exam.show',
                    'my-exam.examTask',
                    'bundle-packaging.ci-to-mobileteam',
                    'receive-exam-materials.headquarters-to-vanduty',
                    'receive-exam-materials.scan-vandutystaff-exam-materials',
                ]
                ],
            'ESCORT' => [
                'ESCORT' => [
                    'cv-down-updates',
                    'route-edit',
                    'otl-lock',
                    'department-officials.edit',
                    'charted-vehicle-routes.edit',
                    'charted-vehicle-routes.downward-journey-routes',
                    'charted-vehicle-routes.save-otl-lock-used',
                    'charted-vehicle-routes.save-gps-lock-used',
                    'viewTrunkboxes',
                ]
                ],
        ],
        'ci' => [
            'ci-meetings.ind',
            'ci-meetings.attendance-QRcode-scan',
            'venues-masters',
            'view-all-other-list',
            'heading',
            'exam-heading',
            'completed-exam.index',
            'ci-assistant.index',
            'ci-assistant.create',
            'ci-assistant.edit',
            'ci-assistant.show',
            'ci-assistant.toggle-status',
            'invigilators.index',
            'invigilators.create',
            'invigilators.edit',
            'invigilators.show',
            'invigilators.toggle-status',
            'scribes.index',
            'scribes.create',
            'scribes.edit',
            'scribes.show',
            'scribes.toggle-status',
            'chief-invigilators.edit',
            'current-exam.index',
            'current-exam.show',
            'my-exam.examTask',
            'my-exam.ciExamActivity',
            'ci-meetings.attendance-QRcode-scan',
            'ci-meetings.updateAdequacyCheck',
            'ci-reports.generate-utilization-certificate',
            'ci-reports.generate-report',
            'qp-box-log.save-time',
            'qp-box-distribution.save-time',
            'ci-paper-replacements.save-replacement-details',
            'ci-candidates-log.savecandidates',
            'ci-candidates-remark.saveremarks',
            'ci-candidates-omrremarks.saveomrremarks',
            'candidate.attendance.save',
            'ci-checklist.save',
            'ci-session-checklist.save',
            'saveVideographyChecklist',
            'saveConsolidateCertificate',
            'saveUtilizationCertificate',
            'staffalloment.save-invigilator-details',
            'staffalloment.view-invigilator-allocate',
            'staffalloment.update-scribe-details',
            'staffalloment.update-ci-assistant-details',
            'bundle-packaging.ci-view',
            'receive-exam-materials.mobileTeam-to-ci-materials',
            'receive-exam-materials.scan-ci-exam-materials',
            'alert-notification.emergency-alert',
            'alert-notification.adequacy-check',
        ],
        'venue' => [
            'venues-masters',
            'heading',
            'view-all-other-list',
            'view-all-chief-invigilators',
            'ci-district-filter',
            'exam-heading',
            'completed-exam.index',
            'ci-assistant.index',
            'ci-assistant.create',
            'ci-assistant.edit',
            'ci-assistant.show',
            'ci-assistant.toggle-status',
            'venues.edit',
            'venues.venue-consent',
            'venues.submit-venue-consent',
            'venues.show-venue-consent',
            'invigilators.index',
            'invigilators.create',
            'invigilators.edit',
            'invigilators.show',
            'invigilators.toggle-status',
            'scribes.index',
            'scribes.create',
            'scribes.edit',
            'scribes.show',
            'scribes.toggle-status',
            'chief-invigilators.index',
            'chief-invigilators.create',
            'chief-invigilators.edit',
            'chief-invigilators.show',
            'chief-invigilators.toggle-status',
            'current-exam.index',
            'current-exam.show',
            'my-exam.examTask',

        ],
        'district' => [
            'receive-exam-materials',
            'scan-exam-materials',
            'showVenueIntimationForm',
            'receive-exam-materials-from-printer',
            'venues-masters',
            'ci-filter',
            'view-all-chief-invigilators',
            'view-all-venue',
            'create-ci-meetings',
            'download-meeting-qr',
            'create-exam-materails-route',
            'receive-bundle-from-mobile-team',
            'district-masters',
            'district.edit',
            'heading',
            'view-all-center',
            'create-exam-materials-route',
            'exam-heading',
            'completed-exam.index',
            'treasury-officers.index',
            'treasury-officers.create',
            'treasury-officers.edit',
            'treasury-officers.show',
            'treasury-officers.toggle-status',
            'centers.index',
            'centers.create',
            'centers.edit',
            'centers.show',
            'centers.toggle-status',
            'mobile-team.index',
            'mobile-team.create',
            'mobile-team.edit',
            'mobile-team.show',
            'mobile-team.toggle-status',
            'venues.index',
            'venues.create',
            'venues.edit',
            'venues.show',
            'venues.destroy',
            'venues.toggle-status',
            'chief-invigilators.index',
            'chief-invigilators.create',
            'chief-invigilators.edit',
            'chief-invigilators.show',
            'chief-invigilators.toggle-status',
            'current-exam.index',
            'current-exam.show',
            'my-exam.examTask',
            'district-candidates.show-venue-intimation-form',
            'district-candidates.review-venue-intimation-form',
            'district-candidates.process-venue-consent-email',
            'district-candidates.clear-saved-venues',
            'district-candidates.updateVenueCenter',
            'generate.qrcode',
            'district-candidates.generatePdf',
            'bundle-packaging.mobileteam-to-district',
            'receive-exam-materials.printer-to-disitrict-treasury',
            'exam-materials-route.index',
            'exam-materials-route.create',
            'exam-materials-route.edit',
            'exam-materials-route.view',
            'district-candidates.exportExcel',
            'district-candidates.resendVenueRequest',
        ],
        'treasury' => [
            'receive-exam-materials-from-printer',
            'receive-bundle-from-mobile-team',
            'exam-heading',
            'completed-exam.index',
            'scan-receive-disitrct-exam-materials',
            'scan-bundle-packaging',
            'treasury-officers.edit',
            'current-exam.index',
            'current-exam.show',
            'my-exam.examTask',
            'bundle-packaging.mobileteam-to-district',
            'bundle-packaging.scan-disitrct-exam-materials',
            'bundle-packaging.save-trunkbox-used-otl-codes',
            'receive-exam-materials.printer-to-disitrict-treasury',
            'receive-exam-materials.scan-disitrct-exam-materials',
        ],
        'center' => [
            'download-meeting-qr',
            'exam-heading',
            'completed-exam.index',
            'centers.edit',
            'current-exam.index',
            'current-exam.show',
            'my-exam.examTask',
            'bundle-packaging.mobileteam-to-center',
            'receive-exam-materials.district-to-center',
            'receive-exam-materials.scan-center-exam-materials',
            'bundle-packaging.scan-center-exam-materials',
            'bundle-packaging.save-center-used-otl-codes',
        ],
        'mobile_team_staffs' => [
            'completed-exam.index',
            'exam-heading',
            'mobile-team.edit',
            'current-exam.index',
            'current-exam.show',
            'my-exam.examTask',
            'bundle-packaging.ci-to-mobileteam',
            'receive-exam-materials.sub-treasury-to-mobile-team',
            'receive-exam-materials.scan-mobile-team-exam-materials',
        ],
        // Add other roles and their permissions
    ];

    public function hasPermission($role, $permission)
    {
        // Check if user is sw-admin first
        if ($role === 'sw-admin') {
            return true; // sw-admin has access to everything
        }
        // if ($permission === 'cv-down-updates' || $permission === 'route-edit' || $permission === 'otl-lock') {
        //     $user = auth()->guard('headquarters')->user();

        //     // Check if the user's dept_off_id exists in EscortStaff
        //     if ($role === 'headquarters' && \App\Models\EscortStaff::where('tnpsc_staff_id', $user->dept_off_id)->exists()) {
        //         return true;
        //     }
        // }
        if ($permission === 'receive-exam-materials-from-printer' || $permission === 'receive-bundle-from-mobile-team') {
            $user = current_user();
            // Check if the user's dept_off_id exists in EscortStaff
            if ($user->district_code === '01') {
                return false; // Re-enabling the return statement
            }
        } 
        // Check if user is logged in through any guard
        if (!isset($this->rolePermissions[$role])) {
            return false;
        }

        if ($role === 'headquarters') {
            $user = auth()->guard('headquarters')->user();
            // If user has 'VDS' as a custom role, set fixed values

            if ($user->custom_role == 'VDS') {
                $department = 'VDS';
                $dept_role = 'VDS';
            }
            elseif ($user->custom_role == 'ESCORT') {
                $department = 'ESCORT';
                $dept_role = 'ESCORT';
            }
            // Check if the user has a role
            else if ($user && $user->role) {
                $department = $user->role->role_department;
                $dept_role = $user->role->role_name;
            } else {
                // If no valid user role exists, return false
                return false;
            }
            return collect($this->rolePermissions[$role][$department][$dept_role] ?? [])
                ->contains(function ($allowedPermission) use ($permission) {
                    return \Illuminate\Support\Str::is($allowedPermission, $permission);
                });
        }

        return collect($this->rolePermissions[$role])
            ->contains(function ($allowedPermission) use ($permission) {
                return \Illuminate\Support\Str::is($allowedPermission, $permission);
            });
    }
}
